/* Strict/permitted autoplay, real missed parcels, small previews and slow originals. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=process.env.DOCK_TEST_OUTPUT||path.join(os.tmpdir(),'dock-boss-phone'),url='http://127.0.0.1:8869/';fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),html=source.replace('  buildBelt(); parcelCache',`  window.__boss={MR,MEDIA,soundEffects,soundtrack,settings,wakeAudio,update,render,syncAudioMix,openBriefing,backToTitle,loadPreview,previewArt,previewImages,pendingPreviews,previewQueue,previewFailed,imageSources,previewFloors,get audio(){return audio;},get state(){return state;},get game(){return game;},get muted(){return muted;},get art(){return pixelArt;},get blocked(){return musicBlocked;}};
 window.__accepted=[];const play=soundEffects.play.bind(soundEffects);soundEffects.play=(kind,options)=>{const ok=play(kind,options);if(ok)__accepted.push(kind);return ok;};
  buildBelt(); parcelCache`);assert.notEqual(source,html);
const checks=[],errors=[],pass=(name,detail)=>{checks.push({name,detail});console.log('PASS '+name+(detail?' · '+JSON.stringify(detail):''));};
async function setup(p,{muted=false,music=true}={}){
 p.on('pageerror',e=>errors.push(e.message));await p.route(url,r=>r.fulfill({contentType:'text/html',body:html}));
 await p.addInitScript(({muted,music})=>{
  requestAnimationFrame=()=>0;localStorage.setItem('dockDashMuted',String(muted));localStorage.setItem('dockDashProfileV2',JSON.stringify({tutorialDone:true,totalDelivered:240,selectedSkin:4}));localStorage.setItem('dockDashSettingsV3',JSON.stringify({location:0,music,sfx:true,musicVolume:.65,rotate:false}));
  window.__contexts=0;const Base=AudioContext;window.AudioContext=class extends Base{constructor(...args){super(...args);__contexts++;}};
 },{muted,music});
}
async function start(p){await p.evaluate(()=>__boss.backToTitle());await p.locator('#start').tap();await p.evaluate(()=>{__boss.update(3.01);__boss.render();});await p.waitForFunction(()=>__boss.audio.state==='running',null,{polling:20});}
async function miss(p,{lives=3,express=false}={}){
 await p.evaluate(()=>__boss.soundEffects.stopAll());await p.waitForFunction(()=>__boss.soundEffects.retiring.size===0,null,{polling:20});
 return p.evaluate(({lives,express})=>{const d=__boss;d.game.lives=lives;d.game.readyIn=0;d.game.hold=0;d.game.parcels=[{type:0,product:0,kind:express?'express':'normal',y:express?400:446,phase:0,expressLeft:express?0:null}];__accepted.length=0;d.update(1/120);d.render();return {accepted:__accepted.slice(),lives:d.game.lives,state:d.state,voices:[...d.soundEffects.voices].map(v=>({duration:v.source.buffer.duration,peak:Math.max(...v.source.buffer.getChannelData(0))}))};},{lives,express});
}
(async()=>{const server=spawn('python',['-m','http.server','8869','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});let strict,permitted;
 try{
  for(let i=0;i<50;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  strict=await chromium.launch({executablePath:process.env.DOCK_CHROME,args:['--no-sandbox','--autoplay-policy=document-user-activation-required']});const context=await strict.newContext({viewport:{width:390,height:664},isMobile:true,hasTouch:true,deviceScaleFactor:2}),p=await context.newPage();await setup(p);await p.goto(url);await p.waitForFunction(()=>__boss.audio&&__boss.blocked,null,{polling:20});
  assert.equal(await p.evaluate(()=>__boss.audio.state),'suspended');assert.equal(await p.evaluate(()=>__contexts),1);assert.equal(await p.locator('.sound:visible .sound-label').textContent(),'Tap for sound');assert.equal(await p.evaluate(()=>__boss.soundtrack.pending),null);
  await p.locator('.sound:visible').tap();await p.waitForFunction(()=>__boss.soundtrack.active&&!__boss.soundtrack.active.player.paused&&!__boss.soundtrack.pending,null,{polling:30});assert.equal(await p.evaluate(()=>__boss.muted),false);assert.equal(await p.evaluate(()=>__contexts),1);assert.equal(await p.evaluate(()=>__boss.soundtrack.active.player.source.loop),true);assert.equal(await p.locator('.sound:visible .sound-label').textContent(),'Sound on');
  pass('blocked automatic playback recovers on the first Sound tap without muting, extra contexts or duplicate loops');
  await p.locator('.sound:visible').tap();assert.equal(await p.evaluate(()=>__boss.muted),true);assert.equal(await p.evaluate(()=>localStorage.getItem('dockDashMuted')),'true');await p.locator('.sound:visible').tap();await p.waitForFunction(()=>__boss.audio.state==='running',null,{polling:20});await p.evaluate(()=>{__boss.settings.music=false;__boss.syncAudioMix();});
  await start(p);const normal=await miss(p);assert.deepEqual(normal.accepted,['miss']);assert.equal(normal.lives,2);assert.ok(normal.voices[0].peak>.7&&normal.voices[0].duration>.3);const express=await miss(p,{express:true});assert.deepEqual(express.accepted,['miss']);assert.equal(express.lives,2);
  pass('actual belt misses and express expiry start the audible warning and remove exactly one life');
  const last=await miss(p,{lives:1});assert.deepEqual(last.accepted,['missEnd']);assert.equal(last.state,'over');assert.ok(last.voices[0].duration>.8);assert.equal(last.voices.length,1);
  await p.evaluate(()=>{__boss.backToTitle();__boss.openBriefing('rome',0);});await p.locator('#mission-launch').tap();await p.evaluate(()=>__boss.update(3.01));const missionLast=await miss(p,{lives:1});assert.deepEqual(missionLast.accepted,['missEnd']);assert.equal(missionLast.state,'missionResult');assert.equal(missionLast.voices.length,1);
  pass('the final miss survives arcade and mission endings as a single warning/result sample');

  const images=await context.newPage();await setup(images,{muted:true});let previewInFlight=0,previewPeak=0;const previewRequests=[],originalRequests=[];
  await images.route('**/assets/previews/*.webp',async r=>{const name=new URL(r.request().url()).pathname.split('/').pop();previewRequests.push(name);if(name==='070.webp')return r.abort('failed');previewInFlight++;previewPeak=Math.max(previewPeak,previewInFlight);await new Promise(resolve=>setTimeout(resolve,80));previewInFlight--;await r.continue();});
  await images.route('**/assets/**/*.png',async r=>{originalRequests.push(new URL(r.request().url()).pathname);await new Promise(resolve=>setTimeout(resolve,2000));await r.continue();});await images.goto(url);await images.waitForFunction(()=>[3,4,5,6].every(i=>__boss.previewArt[i]),null,{polling:20});await images.locator('#missions').tap();await images.evaluate(()=>__boss.render());assert.deepEqual(originalRequests,[]);assert.ok(previewPeak<=4);await images.screenshot({path:path.join(out,'mission-map-phone.png')});
  const logos=await images.evaluate(()=>{const c=document.getElementById('game').getContext('2d'),draw=c.fillText,rows=[];c.fillText=function(s,x,y,...args){if(s==='DOCK BOSS')rows.push({x,y,w:this.measureText(s).width});return draw.call(this,s,x,y,...args);};try{__boss.render();}finally{c.fillText=draw;}return rows;});assert.equal(logos.length,2);assert.ok(logos.every(r=>r.x===170&&r.w<88));
  const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/previews/manifest.json'),'utf8')),first=manifest.images.filter(r=>[3,4,5,6].includes(r.location)),oldBytes=first.reduce((s,r)=>s+r.sourceBytes,0),newBytes=first.reduce((s,r)=>s+r.previewBytes,0);assert.ok(newBytes<oldBytes*.1);pass('the Dock Boss map shows four original world previews with over 90% fewer first-page image bytes and no full-art fetches',{oldBytes,newBytes,previewPeak});
  await images.locator('[data-world="matchday"]').tap();await images.evaluate(()=>__boss.render());assert.equal(await images.evaluate(()=>!!__boss.previewArt[3]&&!__boss.art[3]),true);await images.screenshot({path:path.join(out,'briefing-before-full-art.png')});await images.waitForFunction(()=>__boss.art[3],null,{polling:20,timeout:6000});assert.equal(originalRequests.filter(s=>s.endsWith('/matchday.png')).length,1);pass('briefing artwork is already visible while the original painting is deliberately delayed two seconds');
  await images.evaluate(()=>{const w=__boss.MR.worlds.find(w=>w.location===70);__boss.openBriefing(w.id,0);});await images.waitForFunction(()=>__boss.previewFailed.has(70)&&__boss.art[70],null,{polling:20,timeout:6000});await images.evaluate(()=>{for(let i=0;i<100;i++)__boss.render();});assert.equal(previewRequests.filter(s=>s==='070.webp').length,1);const source70=await images.evaluate(()=>new URL(__boss.MEDIA.floors[70],location.href).pathname);assert.equal(originalRequests.filter(s=>s===source70).length,1);
  const budgets=await images.evaluate(()=>({previews:__boss.previewImages.size,pending:__boss.pendingPreviews.size,queue:__boss.previewQueue.length,full:__boss.imageSources.size,canvases:__boss.previewFloors.entries.size}));assert.ok(budgets.previews<=8&&budgets.pending<=4&&budgets.queue<=8&&budgets.full<=4&&budgets.canvases<=7);
  pass('failed previews recover with original artwork without repeated requests, and image caches stay bounded',budgets);
  for(const size of [{width:320,height:568},{width:390,height:664},{width:414,height:896},{width:844,height:390},{width:1100,height:800}]){await images.setViewportSize(size);await images.locator('#mission-home').tap();await images.locator('#missions').tap();await images.evaluate(()=>__boss.render());const stage=await images.locator('#stage').boundingBox(),home=await images.locator('#mission-home').boundingBox(),story=await images.locator('#mission-journal').boundingBox();assert.ok(home.x+home.width<stage.x+121/360*stage.width&&story.x>stage.x+219/360*stage.width);await images.screenshot({path:path.join(out,`map-${size.width}x${size.height}.png`)});}
  pass('the gold header badge fits between Home and Story in five phone, landscape and desktop layouts');
  await strict.close();strict=null;

  permitted=await chromium.launch({executablePath:process.env.DOCK_CHROME,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});const allowedContext=await permitted.newContext({viewport:{width:390,height:664},isMobile:true,hasTouch:true}),allowed=await allowedContext.newPage();await setup(allowed);await allowed.goto(url);await allowed.waitForFunction(()=>__boss.soundtrack.active&&!__boss.soundtrack.active.player.paused&&!__boss.soundtrack.pending,null,{polling:30});assert.equal(await allowed.evaluate(()=>__boss.state),'title');assert.equal(await allowed.evaluate(()=>__contexts),1);pass('a browser that permits autoplay starts the title music without any tap');
  const quietContext=await permitted.newContext(),quiet=await quietContext.newPage();await setup(quiet,{muted:true});await quiet.goto(url);assert.equal(await quiet.evaluate(()=>__boss.audio),null);assert.equal(await quiet.evaluate(()=>__contexts),0);assert.equal(await quiet.locator('.sound:visible .sound-label').textContent(),'Sound off');assert.equal(await quiet.evaluate(()=>localStorage.getItem('dockDashMuted')),'true');pass('automatic startup preserves saved mute and creates no unwanted audio');
  assert.deepEqual(errors,[]);pass('no browser runtime errors');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors},null,2));
 }finally{await strict?.close();await permitted?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
