/* Search and menu workflows, real keyboard events and responsive hit areas. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=process.env.DOCK_TEST_OUTPUT||path.join(os.tmpdir(),'dock-dash-interface'),url='http://127.0.0.1:8858/';fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),html=source.replace('  buildBelt(); parcelCache',`  window.__dockUI={MR,ER,profile,settings,render,openGarage,openMissionMap,backToTitle,changeShopPage,chooseChapter,imageSources,previewFloors,cargoSprites,
get state(){return state;},get game(){return game;},get wallet(){return wallet;},get selected(){return selectedMission;},get art(){return pixelArt;}};
  buildBelt(); parcelCache`);assert.notEqual(html,source);
const checks=[],errors=[],pass=(name,detail)=>{checks.push({name,detail});console.log('PASS '+name+(detail?' · '+JSON.stringify(detail):''));};
async function paint(p){await p.evaluate(()=>__dockUI.render());}
async function worlds(p){return p.locator('.mission-card:visible').evaluateAll(a=>a.map(b=>b.dataset.world));}
async function items(p){return p.locator('.skin-choice:visible').evaluateAll(a=>a.map(b=>b.dataset.item));}
async function setup(p,coins=2000){await p.route(url,r=>r.fulfill({contentType:'text/html',body:html}));await p.addInitScript(coins=>{requestAnimationFrame=()=>0;localStorage.setItem('dockDashMuted','true');localStorage.setItem('dockDashProfileV2',JSON.stringify({tutorialDone:true,totalDelivered:180,selectedSkin:0}));localStorage.setItem('dockDashWalletV1',JSON.stringify({version:1,coins,earned:coins,spent:0,owned:[]}));},coins);p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.__dockUI&&__dockUI.art[0]);await paint(p);}
async function layout(p){
 const stage=await p.locator('#stage').boundingBox(),boxes=await p.locator('#stage button:visible,#stage input:visible,#stage select:visible').evaluateAll(a=>a.map(b=>{const r=b.getBoundingClientRect();return {id:b.id||b.dataset.world||b.dataset.item,x:r.x,y:r.y,w:r.width,h:r.height};}));
 for(let i=0;i<boxes.length;i++){const a=boxes[i];assert.ok(a.x>=stage.x-.6&&a.x+a.w<=stage.x+stage.width+.6&&a.y>=stage.y-.6&&a.y+a.h<=stage.y+stage.height+.6,JSON.stringify(a));for(let j=i+1;j<boxes.length;j++){const b=boxes[j];assert.equal(a.x<b.x+b.w-.5&&a.x+a.w>b.x+.5&&a.y<b.y+b.h-.5&&a.y+a.h>b.y+.5,false,JSON.stringify({a,b}));}}
}
(async()=>{const server=spawn('python',['-m','http.server','8858','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});let browser;
try{for(let i=0;i<40;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({executablePath:process.env.DOCK_CHROME||'/root/.cache/ms-playwright/dock-dash-chrome/chrome-headless-shell',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2}),p=await context.newPage();await setup(p);
assert.match(await p.locator('#start').textContent(),/Arcade.*Endless shifts/);assert.match(await p.locator('#missions').textContent(),/Missions.*179 places/);await p.screenshot({path:path.join(out,'home.png')});pass('Home makes both modes and their purpose visible before starting a game');
await p.locator('#missions').tap();await p.getByRole('searchbox',{name:'Search world names and themes in the selected chapter'}).fill('Moon Orchard');await paint(p);assert.deepEqual(await worlds(p),['moonorchard']);assert.equal(await p.locator('#missions-next').isDisabled(),true);await p.locator('[data-world="moonorchard"]').tap();assert.equal(await p.evaluate(()=>__dockUI.selected.id),'moonorchard-1');await p.locator('#briefing-back').tap();assert.equal(await p.locator('#mission-search').inputValue(),'Moon Orchard');assert.deepEqual(await worlds(p),['moonorchard']);pass('a multiword search reaches its exact world and returning from briefing keeps the results');
await p.locator('#mission-chapter').selectOption('greenwood');assert.deepEqual(await worlds(p),[]);assert.equal(await p.locator('#missions-continue').isDisabled(),true);assert.equal(await p.locator('#missions-prev').isDisabled(),true);assert.equal(await p.locator('#missions-next').isDisabled(),true);await paint(p);await p.screenshot({path:path.join(out,'world-empty-state.png')});assert.equal(await p.locator('#mission-clear').isVisible(),true);await p.locator('#mission-clear').tap();assert.ok((await worlds(p)).includes('greenwood'));assert.equal(await p.locator('#missions-continue').isDisabled(),false);pass('search combines with chapters and an empty result has safe controls and a working clear action');
await p.locator('#mission-chapter').selectOption('');await p.locator('#mission-search').fill('');await p.locator('#mission-search').pressSequentially('p1234');assert.equal(await p.locator('#mission-search').inputValue(),'p1234');assert.equal(await p.evaluate(()=>__dockUI.state),'missions');await p.locator('#mission-search').press('Escape');assert.equal(await p.evaluate(()=>__dockUI.state),'missions');assert.equal(await p.locator('#mission-search').inputValue(),'');await p.locator('#mission-search').fill('moon');await p.locator('#mission-search').press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'');assert.equal(await p.evaluate(()=>__dockUI.game),null);pass('real typing retains digits and P, while Escape clears and Enter dismisses search without starting gameplay');
await p.locator('#mission-search').fill('story');let seen=[];while(true){seen.push(...await worlds(p));if(await p.locator('#missions-next').isDisabled())break;await p.locator('#missions-next').tap();}assert.equal(new Set(seen).size,seen.length);assert.ok(seen.length>4);await p.locator('#mission-search').fill('   ');assert.equal((await worlds(p))[0],'matchday');pass('matching worlds page without duplicates and blank searches restore normal browsing',{results:seen.length});
await p.locator('#mission-home').tap();await p.locator('.fleet-button:visible').tap();const original=await items(p);assert.ok(original.includes('school'));await p.locator('#shop-search').fill('Goal Getter');assert.deepEqual(await items(p),['matchday']);const before=await p.evaluate(()=>__dockUI.wallet.coins),price=await p.evaluate(()=>__dockUI.ER.item('matchday').price);await p.locator('[data-item="matchday"]').tap();assert.equal(await p.evaluate(()=>__dockUI.wallet.coins),before-price);assert.equal(await p.locator('[data-item="matchday"]').getAttribute('aria-pressed'),'true');await p.locator('#shop-owned').tap();assert.deepEqual(await items(p),['matchday']);await p.locator('[data-item="matchday"]').tap();assert.equal(await p.evaluate(()=>__dockUI.wallet.coins),before-price);pass('buying from search equips the correct truck and Owned results never charge twice');
await p.locator('#shop-search').fill('');await p.locator('#shop-owned').tap();assert.deepEqual(await items(p),original);await p.locator('#shop-next').tap();const remembered=await items(p);await p.locator('#shop-search').fill('prism');await p.locator('#shop-search').fill('');assert.deepEqual(await items(p),remembered);pass('clearing shop search restores the prior category page');
await p.locator('[data-shop="venues"]').tap();await p.locator('#shop-search').fill('Moon Orchard');assert.deepEqual(await items(p),['venue:moonorchard']);await p.locator('#shop-owned').tap();assert.deepEqual(await items(p),[]);assert.equal(await p.locator('#shop-clear').isVisible(),true);await p.locator('#shop-owned').tap();assert.deepEqual(await items(p),['venue:moonorchard']);await paint(p);await p.waitForFunction(()=>{__dockUI.render();return __dockUI.art[__dockUI.MR.worlds.find(w=>w.id==='moonorchard').location];});await p.screenshot({path:path.join(out,'shop-search.png')});pass('shop search combines with category and ownership while keeping individual world previews');
const poor=await context.newPage();await setup(poor,100);await poor.locator('.fleet-button:visible').tap();await poor.locator('#shop-search').fill('Beacon Wagon');await paint(poor);const labels=await poor.evaluate(()=>{const old=CanvasRenderingContext2D.prototype.fillText,all=[];CanvasRenderingContext2D.prototype.fillText=function(str,...args){if(this.canvas.id==='game')all.push(str);return old.call(this,str,...args);};try{__dockUI.render();}finally{CanvasRenderingContext2D.prototype.fillText=old;}return all;});const cost=await poor.evaluate(()=>__dockUI.ER.item('beacon').price);assert.ok(labels.includes(`COST · ${cost} COINS`));assert.ok(labels.includes(`${cost-100} MORE COINS`));await poor.locator('[data-item="beacon"]').tap();assert.equal(await poor.evaluate(()=>__dockUI.wallet.coins),100);assert.match(await poor.locator('#shop-message').textContent(),/Need/);await poor.screenshot({path:path.join(out,'coin-gap.png')});pass('unaffordable items show their cost and missing coins while a tap keeps the wallet unchanged');await poor.close();
await p.locator('#shop-search').fill('');await p.locator('#garage-back').tap();
for(const size of [{width:320,height:568},{width:390,height:844},{width:430,height:932},{width:844,height:390},{width:1280,height:800}]){await p.setViewportSize(size);await p.evaluate(()=>window.dispatchEvent(new Event('resize')));for(const state of ['title','missions','garage']){await p.evaluate(state=>{__dockUI.backToTitle();if(state==='missions')__dockUI.openMissionMap();else if(state==='garage')__dockUI.openGarage();__dockUI.render();},state);await layout(p);if(size.width===320&&state==='title'){assert.ok((await p.locator('#start').boundingBox()).height>=54);await p.screenshot({path:path.join(out,'small-phone-home.png')});}}}pass('Home, world search and shop controls remain separate and contained in five screen sizes');
const cache=await p.evaluate(()=>({images:__dockUI.imageSources.size,previews:__dockUI.previewFloors.entries.size,cargo:__dockUI.cargoSprites.entries.size}));assert.ok(cache.images<=12&&cache.previews<=7&&cache.cargo<=144);pass('search stays within existing phone image and cargo memory budgets',cache);
assert.deepEqual(errors,[]);pass('no browser runtime errors');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors},null,2));
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
