/* Rebranding keeps old saves; help, sharing and practice work through native controls. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=process.env.DOCK_TEST_OUTPUT||path.join(os.tmpdir(),'dock-boss-release'),url='http://127.0.0.1:8868/';fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),html=source.replace('  buildBelt(); parcelCache',`  window.__release={BRAND,MR,ER,render,update,backToTitle,saveSnapshot,backups,shareGame,get state(){return state;},get game(){return game;},get tutorial(){return tutorial;}};
  buildBelt(); parcelCache`);assert.notEqual(source,html);
const checks=[],errors=[],pass=(name,detail)=>{checks.push({name,detail});console.log('PASS '+name+(detail?' · '+JSON.stringify(detail):''));};
async function snap(p){return p.evaluate(()=>__release.saveSnapshot());}
async function reveal(p,id){await p.locator('#'+id).evaluate(e=>{const scroll=e.closest('.help-content');if(scroll){const r=e.getBoundingClientRect(),s=scroll.getBoundingClientRect();scroll.scrollTop+=r.top-s.top-8;}});}
(async()=>{const server=spawn('python',['-m','http.server','8868','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});let browser;
 try{
  for(let i=0;i<50;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({executablePath:process.env.DOCK_CHROME,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:390,height:664},isMobile:true,hasTouch:true,deviceScaleFactor:2,acceptDownloads:true}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
  await p.route(url,r=>r.fulfill({contentType:'text/html',body:html}));await p.addInitScript(()=>{
   requestAnimationFrame=()=>0;localStorage.setItem('dockDashMuted','true');localStorage.setItem('dockDashBest','12345');
   localStorage.setItem('dockDashProfileV2',JSON.stringify({tutorialDone:true,totalDelivered:240,totalPerfect:80,totalTrucks:40,totalGoals:20,highestShift:12,selectedSkin:4}));
   localStorage.setItem('dockDashWalletV1',JSON.stringify({version:1,coins:5000,earned:7000,spent:2000,owned:['school','venue:rome']}));
   localStorage.setItem('dockDashSettingsV3',JSON.stringify({location:13,music:false,sfx:true,musicVolume:.42,rotate:false,effects:'auto'}));
   localStorage.setItem('dockDashMissionsV1',JSON.stringify({'rome-1':{stars:3,bestScore:1600,bestTime:23.12}}));localStorage.setItem('dockDashCargoCollectionV1','[3,14,29]');
  });await p.goto(url);await p.waitForFunction(()=>window.__release,null,{polling:50});
  const initial=await snap(p),gameURL=await p.evaluate(()=>__release.BRAND.url);assert.equal(initial.wallet.coins,5000);assert.equal(initial.best,12345);assert.equal(initial.profile.selectedSkin,4);assert.equal(initial.settings.location,13);assert.equal(initial.missions['rome-1'].stars,3);
  assert.equal(await p.title(),'Dock Boss — The Hundred Lanterns');assert.equal(await p.locator('meta[name="apple-mobile-web-app-title"]').getAttribute('content'),'Dock Boss');assert.equal(await p.locator('meta[property="og:url"]').getAttribute('content'),gameURL);
  const manifest=await (await p.request.get(url+'manifest.webmanifest')).json();assert.equal(manifest.name,'Dock Boss — The Hundred Lanterns');assert.equal(manifest.short_name,'Dock Boss');assert.equal(manifest.id,'./');assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./index.html');assert.match(manifest.description,/hundred worlds.*800/i);assert.doesNotMatch(manifest.description,/Batman|Batmobile|Batcave/i);
  const titleInk=await p.evaluate(()=>{const c=document.getElementById('game').getContext('2d'),draw=c.fillText,ink=[];c.fillText=function(s,x,y,...rest){if(['DOCK','BOSS'].includes(s))ink.push({s,x,y,width:this.measureText(s).width});return draw.call(this,s,x,y,...rest);};try{__release.render();}finally{c.fillText=draw;}return ink;});assert.deepEqual(titleInk.map(t=>t.s),['DOCK','BOSS']);assert.ok(titleInk.every(t=>t.width<=316&&t.x-t.width/2>=21));await p.screenshot({path:path.join(out,'home-phone.png')});
  pass('new title, install identity and link previews retain existing coins, stars, equipment and the app URL');

  await p.locator('#learn').tap();assert.equal(await p.locator('#help-dialog').isVisible(),true);assert.equal(await p.evaluate(()=>__release.state),'title');assert.deepEqual(await snap(p),initial);assert.equal(await p.locator('#help-link').inputValue(),gameURL);assert.match(await p.locator('#help-content').textContent(),/100 worlds and 800 missions/);await p.screenshot({path:path.join(out,'help-phone.png')});
  await p.keyboard.press('Escape');assert.equal(await p.locator('#help-dialog').isVisible(),false);assert.equal(await p.locator('#learn').evaluate(e=>e===document.activeElement),true);assert.equal(await p.evaluate(()=>__release.state),'title');await p.locator('#learn').tap();
  pass('help explains delivery, missions, coins and backups; Escape returns focus without starting a game');

  const footer=await p.locator('.help-actions').boundingBox(),scroll=await p.locator('#help-content').boundingBox(),cdp=await context.newCDPSession(p),x=scroll.x+scroll.width*.7,y=scroll.y+scroll.height*.8;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-scroll.height*.65*i/8}]});await new Promise(r=>setTimeout(r,20));}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await p.waitForFunction(()=>document.getElementById('help-content').scrollTop>20,null,{polling:50});assert.deepEqual(await p.locator('.help-actions').boundingBox(),footer);assert.equal(await p.locator('#stage').evaluate(e=>e.scrollTop),0);
  pass('real touch swipes scroll instructions while practice and Back to home stay fixed');

  await p.evaluate(()=>{window.__shares=[];window.__copies=[];Object.defineProperty(navigator,'canShare',{configurable:true,value:data=>!data.files});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>__shares.push(data)});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>__copies.push(text)}});});await reveal(p,'help-share');await p.locator('#help-share').tap();await p.waitForFunction(()=>!document.getElementById('help-share').disabled,null,{polling:50});assert.deepEqual(await p.evaluate(()=>__shares),[{title:'Dock Boss — The Hundred Lanterns',text:'One parcel. A hundred worlds. Play this pixel-art delivery adventure.',url:gameURL}]);assert.deepEqual(await snap(p),initial);
  pass('native sharing receives only the public game link and branding, without save data or coin changes');

  await p.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:async()=>{throw new DOMException('cancel','AbortError');}}));await p.locator('#help-share').tap();await p.waitForFunction(()=>!document.getElementById('help-share').disabled,null,{polling:50});assert.equal(await p.locator('#help-share-status').textContent(),'Sharing cancelled.');assert.deepEqual(await p.evaluate(()=>__copies),[]);
  await p.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:data=>new Promise(resolve=>{__shares.push(data);window.__finishShare=resolve;})}));await p.locator('#help-share').tap();assert.equal(await p.locator('#help-share').isDisabled(),true);await p.evaluate(()=>__release.shareGame());assert.equal(await p.evaluate(()=>__shares.length),2);await p.evaluate(()=>__finishShare());await p.waitForFunction(()=>!document.getElementById('help-share').disabled,null,{polling:50});
  pass('cancelled sharing stays cancelled and pending share sheets cannot be opened twice');

  await p.evaluate(()=>Object.defineProperty(navigator,'share',{configurable:true,value:undefined}));await p.locator('#help-close').tap();await p.locator('#learn').tap();assert.equal(await p.locator('#help-share').textContent(),'Copy game link');await reveal(p,'help-share');await p.locator('#help-share').tap();await p.waitForFunction(()=>!document.getElementById('help-share').disabled,null,{polling:50});assert.deepEqual(await p.evaluate(()=>__copies),[gameURL]);assert.match(await p.locator('#help-share-status').textContent(),/copied/);
  await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined}));await p.locator('#help-share').tap();await p.waitForFunction(()=>!document.getElementById('help-share').disabled,null,{polling:50});assert.equal(await p.locator('#help-share-status').textContent(),'Copy the game link above.');assert.equal(await p.locator('#help-link').evaluate(e=>e===document.activeElement&&e.readOnly),true);assert.equal(await p.locator('#stage').evaluate(e=>e.scrollTop),0);assert.deepEqual(await snap(p),initial);
  pass('browsers without a share sheet copy the link, with a readable manual fallback when clipboard access is unavailable');

  const layouts=[];for(const size of [{width:320,height:568},{width:390,height:664},{width:414,height:896},{width:844,height:390},{width:1100,height:800}]){
   await p.setViewportSize(size);await p.locator('#help-content').evaluate(e=>e.scrollTop=0);const bounds=await p.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {dialog:box(document.getElementById('help-dialog')),header:box(document.querySelector('#help-dialog>header')),scroll:box(document.getElementById('help-content')),footer:box(document.querySelector('.help-actions'))};});const d=bounds.dialog;
   assert.ok(d.x>=0&&d.y>=0&&d.x+d.w<=size.width+.5&&d.y+d.h<=size.height+.5,JSON.stringify({size,bounds}));assert.ok(bounds.header.y+bounds.header.h<=bounds.scroll.y+1&&bounds.scroll.y+bounds.scroll.h<=bounds.footer.y+1,JSON.stringify({size,bounds}));assert.ok(bounds.scroll.h>40,JSON.stringify({size,bounds}));assert.equal(await p.locator('#help-content').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);
   for(const id of ['help-practice','help-close','help-share','help-link']){await reveal(p,id);const r=await p.locator('#'+id).boundingBox();assert.ok(r.height>=43.5&&r.x>=d.x&&r.x+r.width<=d.x+d.w+.5,JSON.stringify({size,id,r,d}));}
   assert.equal(await p.locator('#help-dialog button').filter({hasText:'Back to home'}).count(),1);await p.locator('#help-content').evaluate(e=>e.scrollTop=0);await p.screenshot({path:path.join(out,`help-${size.width}x${size.height}.png`)});layouts.push(size);
  }pass('five layouts keep instructions scrollable, controls at least 44 pixels and a single fixed Home action',layouts);

  await p.setViewportSize({width:390,height:664});await p.locator('#help-practice').tap();assert.equal(await p.locator('#help-dialog').isVisible(),false);assert.equal(await p.evaluate(()=>__release.state),'play');assert.equal(await p.evaluate(()=>__release.game.readyIn),3);assert.equal(await p.evaluate(()=>__release.tutorial.step),0);assert.equal(await p.locator('#lanes').isVisible(),false);assert.deepEqual(await snap(p),initial);await p.evaluate(()=>{__release.update(3.01);__release.render();});assert.equal(await p.locator('#lanes').isVisible(),true);assert.deepEqual(await snap(p),initial);await p.evaluate(()=>__release.backToTitle());
  pass('optional practice starts with the three-second countdown and keeps the player’s earned progress');

  await p.locator('.settings-button:visible').tap();await p.locator('#preferences-open').tap();const legacyText=fs.readFileSync(path.join(root,'tests/fixtures/dock-dash-v1-backup.json'),'utf8'),legacy=await p.evaluate(t=>__release.backups.read(t).data,legacyText),chooser=p.waitForEvent('filechooser');await p.locator('#backup-import').tap();await (await chooser).setFiles({name:'dock-dash-backup-2026-10-07.json',mimeType:'application/json',buffer:Buffer.from(legacyText)});await p.locator('#backup-preview').waitFor({state:'visible'});assert.deepEqual(await snap(p),initial);await p.locator('#backup-restore').tap();assert.deepEqual(await snap(p),legacy);await p.locator('#backup-undo').tap();assert.deepEqual(await snap(p),initial);
  const downloadEvent=p.waitForEvent('download');await p.locator('#backup-export').tap();const download=await downloadEvent,exported=fs.readFileSync(await download.path(),'utf8');assert.match(download.suggestedFilename(),/^dock-boss-backup-/);assert.equal(JSON.parse(exported).game,'Dock Boss');assert.deepEqual(await p.evaluate(t=>__release.backups.read(t).data,exported),initial);
  pass('a genuine pre-rebrand backup previews, restores and undoes exactly, and new exports use the new name');
  assert.deepEqual(errors,[]);pass('no browser runtime errors');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors},null,2));
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
