/* The Hundred Lanterns: original settings, keepers and a connected courier story. */
(function(root,factory){
  const pack=factory();
  if(typeof module==='object'&&module.exports)module.exports=pack;
  else root.DockDashWorldPack=pack;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const title='The Hundred Lanterns';
  const prologue='Once, a hundred lanterns joined distant places into one bright road. A quiet storm scattered their light. You inherit a little delivery dock and a map of the missing keepers. Carry what each community needs, listen to its story, and help its lantern shine again. Every world has eight chapters; every final delivery brings another light home.';
  const chapters={
    greenwood:{name:'GREENWOOD',keeper:'Rowan',story:'Rowan is an apprentice archer who carries bread as often as arrows. With the forest paths closed, she asks you to help the villages reconnect. Her greatest shot will carry a rope across a broken bridge.',scene:'greenwood',accent:'#bddd95',voice:'plucked'},
    tidebound:{name:'TIDEBOUND',keeper:'Mira',story:'Mira keeps a tide chart that belonged to her grandmother. Its forgotten coves still have communities waiting for news. Follow her little boat from coral gardens to the last lighthouse.',scene:'coral',accent:'#95e4df',voice:'pan'},
    skyroads:{name:'SKY ROADS',keeper:'Ivo',story:'Ivo builds kites large enough to carry letters. Above the clouds, islands have drifted apart. Supplies, patient hands and one brave flight can join them again.',scene:'cloud',accent:'#c7dbff',voice:'bell'},
    wildheart:{name:'WILD HEART',keeper:'Nia',story:'Nia studies the trails of animals, not treasure. The lanterns here warm nurseries, guide migrating flocks and protect fragile habitats. Help people make room for the wild.',scene:'jungle',accent:'#b7e9a9',voice:'marimba'},
    clockwork:{name:'CLOCKWORK',keeper:'Tess',story:'Tess once built a perfect clock and forgot to make time for her friends. Now her machines mend rather than hurry. Help her give a busy city its evenings back.',scene:'workshop',accent:'#a2eee3',voice:'chip'},
    hearthside:{name:'HEARTHSIDE',keeper:'Sol',story:'Sol collects recipes on the backs of old delivery receipts. Each kitchen has a memory worth sharing. The final feast will have a seat for every keeper.',scene:'village',accent:'#ffd8a3',voice:'keys'},
    echoes:{name:'ECHOES',keeper:'Asha',story:'Asha restores letters that nobody remembers sending. Follow trade roads and lost workshops through imagined historical communities. Their lanterns preserve everyday people, not just kings.',scene:'temple',accent:'#eacb94',voice:'plucked'},
    starlight:{name:'STARLIGHT',keeper:'Lumi',story:'Lumi is the last keeper, a small astronomer with an enormous telescope. The scattered lights are stars on a map of home. Bring the hundred communities together for a dawn they can all see.',scene:'cosmos',accent:'#d3c2ff',voice:'bell'}
  };
  // id, name, scene, landmark, keeper, opening, turning point, ending, eight chapter titles, twelve cargo entries.
  // These are authored places with their own local problem, discovery and resolution.
  const rows=[
    ['greenwood','Greenwood Post','greenwood','archery','Rowan','Rowan finds a letter tied to an arrow: the forest villages have lost their road.','The letter is from her missing mentor, waiting beyond a fallen oak.','Rowan sends a rope arrow across the gap. The first forest road opens.','Arrow letter|Bowyer morning|Lost footpath|Oak crossing|Ranger relay|Mentor trail|Bridge supplies|The first lantern','Longbows|longbow;Arrow bundles|quiver;Ranger satchels|satchel;Feather fletchings|feather;Target boards|target;Leather bracers|bracer;Hooded cloaks|cloak;Trail maps|map;Rope coils|rope;Seed loaves|breadloaf;Woodland lanterns|lantern;Carved whistles|flute'],
    ['oakmarket','Oakroot Market','greenwood','market','Bryn','Bryn plants a market beneath an oak where travellers once shared their meals.','A forgotten seed chest holds crops for every village, not a hidden fortune.','The market returns. Nobody leaves the oak without food for the road.','Empty stalls|Seed chest|Miller visit|Basket crossing|Trading paths|Market canopy|Village supper|Oakroot reunion','Seed baskets|basket;Oat bread|breadloaf;Market apples|fruitcrate;Honey jars|jar;Linen cloths|linen;Wooden bowls|bowl;Hand scales|gemscale;Trade tokens|coins;Canvas awnings|tent;Herb bunches|plant;Stall lanterns|lantern;Market ledgers|book'],
    ['foxbridge','Foxbridge','greenwood','bridge','Edda','Edda keeps a ferry at a bridge whose last stones fell during the storm.','An old bridge plan fits the river better than the grand design in the castle.','Neighbours build the humble bridge together. Edda becomes its first toll-free guide.','Ferry landing|Mason crates|River survey|Old bridge plan|Timber passage|Arch supports|Lantern rails|A bridge for all','Bridge timbers|steelbeam;Mason tools|hammer;Rope bundles|rope;Stone blocks|stoneblock;Iron nails|tools;Survey rulers|ruler;River charts|map;Canvas shelters|tent;Work gloves|gloves;Hot soup|soupbowl;Rail lanterns|lantern;Bridge sketches|blueprint'],
    ['willowkeep','Willow Keep','castle','castle','Ada','Ada guards a keep whose locked storehouse is full while nearby homes are empty.','Its old charter says the stores belong to the valley in times of need.','The gates open as a community depot. Ada keeps the charter above the door.','Closed gate|Quartermaster|Charter search|Storehouse keys|Valley convoy|Open courtyard|Winter parcels|The shared keep','Storehouse keys|oldkey;Grain sacks|bag;Valley charter|scroll;Training shields|roundshield;Linen tunics|tunic;Water barrels|barrel;Repair hammers|hammer;Stable feed|feed;Gate lanterns|lantern;Garden seedlings|plant;Blanket rolls|blanket;Supply ledgers|book'],
    ['moonarchery','Moonbow Range','greenwood','archery','Finn','Finn can hit every target but has never delivered a parcel on time.','A lost child follows the range lanterns home, giving every target a new purpose.','Finn turns the contest into a lantern trail. Precision becomes a way to help.','Practice arrows|Target trail|Missing scout|Range repairs|Lantern course|Rope-shot test|Night guide|The helpful shot','Practice bows|longbow;Training arrows|quiver;Painted targets|target;Scout badges|herobadge;Waxed bowstrings|rope;Ranger caps|cap;Trail whistles|flute;Warm cloaks|cloak;Signal lanterns|lantern;First-aid packs|firstaid;Berry flasks|thermos;Prize ribbons|bow'],
    ['thistlemill','Thistle Mill','greenwood','windmill','Oren','Oren hears the mill wheel turning but no flour reaches the village.','A family of otters has made a home in the blocked channel.','A new side channel leaves the otters safe and brings the mill back to life.','Silent mill|Grain baskets|Waterwheel tools|Otter channel|Flour relay|Village ovens|River celebration|Bread at sunrise','Grain bundles|wheat;Mill gears|gear;Flour sacks|floursack;Baking trays|board;Waterwheel paddles|paddle;Canal stones|stoneblock;Otter habitat kits|house;Seed bread|breadloaf;Honey croissants|croissant;Wooden scoops|cutlery;Mill aprons|tunic;Dawn lanterns|lantern'],
    ['fernhollow','Fern Hollow','greenwood','herbs','Lark','Lark learns remedies from a grandmother whose garden survived the storm.','The rarest medicine is ordinary clean water brought from the next village.','A little clinic opens among the ferns. Lark adds every neighbour to her book.','Garden notes|Herbal baskets|Spring water|Clinic canopy|Careful remedies|Village rounds|Healing supper|A kinder hollow','Herb baskets|basket;Clean water|watercrate;Remedy jars|potion;Cotton bandages|firstaid;Garden trowels|tools;Fern seedlings|plant;Clay cups|cup;Recipe notes|notebook;Soft blankets|blanket;Glass droppers|bottle;Bee balm flowers|lotus;Clinic lanterns|lantern'],
    ['dawnwood','Dawnwood Fair','castle','festival','Rowan','Rowan invites every forest village to the keep for one shared fair.','Her mentor returns carrying the map fragment that the forest lanterns reveal.','Eight forest lights become one route. Rowan sends the map onward with you.','Fair invitations|Banner stitchers|Forest arrivals|Map reunion|Archery gifts|Community feast|Keeper gathering|Dawnwood light','Fair invitations|ticket;Festival banners|flag;Lantern frames|lantern;Carved flutes|flute;Archery prizes|medal;Apple baskets|fruitcrate;Feast platters|plate;Canvas stalls|tent;Painted shields|roundshield;Story scrolls|scroll;Map fragments|map;Keeper wreaths|laurel'],
    ['coralhaven','Coral Haven','coral','reef','Mira','Mira follows a faded tide chart to a reef nursery dimmed by drifting debris.','A tiny coral colony still glows beneath the sand, marking a safe channel.','The nursery lights again. Mira draws its hidden channel on the family chart.','Reef arrival|Nursery baskets|Hidden channel|Clean-water relay|Coral shelter|Diver lanterns|Reef watch|The living light','Coral cuttings|coral;Diving masks|goggles;Nursery tools|tools;Reef charts|map;Water filters|sensor;Seaweed seedlings|plant;Sample jars|jar;Repair ropes|rope;Floating buoys|lifebuoy;Marine cameras|camera;Care gloves|gloves;Reef lanterns|lantern'],
    ['pearlquay','Pearl Quay','harbour','market','Sena','Sena sells pearls to keep the harbour library open.','A pearl hides a rolled letter promising books from an inland town.','The shelves fill with donated stories. The rare pearl stays in the reading room.','Pearl baskets|Quiet library|Bottle letter|Book convoy|Reading pier|Harbour parcels|Story exchange|Pearl of the quay','Pearl boxes|pearl;Library books|bookstack;Bottle letters|bottle;Reading lamps|lamp;Harbour baskets|basket;Trade scales|gemscale;Sail patches|linen;Ink pots|jar;Dock ropes|rope;Sea maps|map;Book satchels|satchel;Library keys|oldkey'],
    ['kelpforest','Kelp Forest','coral','kelp','Ola','Ola tends a floating garden where the kelp has stopped swaying.','The storm moved a sunken gate that blocks the gentle current.','The current returns without disturbing the nursery. Silver fish find their way home.','Floating garden|Kelp seedlings|Current survey|Sunken gate|Nursery shelter|Ocean gardeners|Silver shoals|The flowing forest','Kelp seedlings|plant;Current sensors|sensor;Garden floats|lifebuoy;Gate tools|hammer;Diver flippers|flipper;Rope ladders|rope;Ocean notebooks|notebook;Shell shelters|shell;Filter kits|tools;Sea tea|jar;Sample bottles|bottle;Garden beacons|beacon'],
    ['saltwind','Saltwind Port','harbour','sailboat','Jori','Jori repairs boats using scraps from a hundred different journeys.','The unfinished boat is meant for a neighbour who has never seen the sea.','The neighbour takes the helm. Jori names the boat Tomorrow.','Scrap landing|Sailmakers|Neighbour letter|Hull repairs|Rigging relay|First provisions|Launch gathering|Tomorrow sails','Sailcloth rolls|linen;Hull planks|steelbeam;Ship ropes|rope;Brass compasses|compass;Paint tins|paintcan;Deck lanterns|lantern;Repair hammers|hammer;Voyage food|breadloaf;Water barrels|barrel;Boat models|reedboat;Life jackets|lifevest;Launch pennants|flag'],
    ['turtlebay','Turtle Bay','coral','nursery','Ari','Ari notices baby turtles turning toward the bright village instead of the water.','The old lantern lenses can shade the beach while still lighting the homes.','The hatchlings reach the sea. The village learns to share its night.','Beach watch|Hatchery kits|Lens delivery|Shaded lights|Quiet shoreline|Turtle trail|Village watch|A shared night','Shade lenses|lens;Hatchery sand|bag;Beach markers|flag;Turtle shelters|house;Night cameras|camera;Soft gloves|gloves;Clean buckets|bowl;Survey maps|map;Repair kits|tools;Seaweed bundles|plant;Volunteer badges|herobadge;Low-glow lanterns|lantern'],
    ['stormharbour','Storm Harbour','harbour','lighthouse','Mira','Mira arrives before the storm to find the harbour bell missing.','The bell is in a repair shed, ready to ring if the crew can reach every dock.','All boats come home before the squall. The bell rings for the last arrival.','Weather letter|Harbour kits|Bell foundry|Mooring lines|Shelter supplies|Four-dock watch|Last boat home|The homecoming bell','Harbour bells|bell;Mooring ropes|rope;Warm blankets|blanket;Weather radios|radio;Signal flares|torch;Shelter meals|soupbowl;Medical kits|firstaid;Water crates|watercrate;Mast lamps|lantern;Repair boards|board;Life rings|lifebuoy;Harbour charts|map'],
    ['glasslagoon','Glass Lagoon','coral','glasshouse','Vela','Vela makes window glass from discarded bottles washed onto the lagoon.','Her first clear pane shows the empty classroom across the water.','The classroom gains bright windows. Its pupils send Vela a picture of the sea.','Bottle shore|Glass sorting|Clear first pane|Classroom frames|Window convoy|Careful fittings|School colours|A sea-view lesson','Glass bottles|bottle;Clear panes|lens;Window frames|board;Glazier gloves|gloves;Polishing brushes|brush;Classroom sketches|palette;Tool kits|tools;Recycled tiles|stoneblock;Packing cloth|linen;School books|bookstack;Safety goggles|goggles;Lagoon lights|lantern'],
    ['mangroveroot','Mangrove Reach','coral','mangrove','Dara','Dara ferries supplies through roots that shelter the smallest fish.','A proposed straight road would drain the nursery. An old raised path offers a kinder route.','A wooden walkway reconnects the homes and leaves the tidal forest alive.','Root channels|Raised-path plan|Nursery survey|Walkway timbers|Tide relay|Household parcels|Root-side feast|The gentle road','Walkway timber|steelbeam;Tide maps|map;Nursery baskets|basket;Wooden pegs|tools;Mangrove seedlings|plant;Water sensors|sensor;Raised-path plans|blueprint;Handrails|rope;Family meals|takeaway;Fishing floats|lifebuoy;Work boots|workboot;Path lanterns|lantern'],
    ['whalesong','Whalesong Pier','harbour','observatory','Pip','Pip records whales from a pier where nobody has heard their song this year.','A noisy generator is masking the music; sunlight can power the recorder instead.','The pier falls quiet. A whale answers, and Pip sends its song along the coast.','Listening pier|Recorder parts|Silent power|Solar fittings|Signal relay|Ocean notebooks|First reply|A song returns','Listening sensors|sensor;Solar panels|solar;Recorder drives|serverdrive;Headphones|headphones;Pier tools|tools;Sound notebooks|notebook;Power cells|powercell;Ocean cameras|camera;Weather kits|radio;Cable coils|cablereel;Research flasks|thermos;Quiet beacons|beacon'],
    ['horizonlight','Horizon Light','harbour','lighthouse','Mira','Mira reaches the lighthouse drawn at the edge of her grandmother\'s chart.','Its keeper left a lens that scatters light into the shape of a wing.','The coast lights connect. The wing points your next journey toward the sky.','Last coastline|Keeper provisions|Winged lens|Tower repairs|Coastal relay|Light calibration|Keeper farewell|Beyond the horizon','Lighthouse lenses|lens;Tower tools|tools;Keeper provisions|breadloaf;Brass compasses|compass;Light prisms|lightprism;Signal flags|flag;Oil flasks|bottle;Weather charts|map;Warm coats|parka;Bell fittings|bell;Glass shields|heroshield;Horizon lanterns|lantern'],
    ['cloudpost','Cloud Post','cloud','airship','Ivo','Ivo catches a letter blown down from an island above the clouds.','Its sender is a child who thinks the ground has forgotten them.','A kite carries your reply. The child draws the first safe sky route.','Windblown letter|Kite cloth|Skyward reply|Cloud landing|Parcel wings|Island mail|Little mapmaker|The first sky road','Kite frames|kite;Letter bundles|mailbundle;Cloud maps|map;Silk sailcloth|silkrolls;Wind gauges|weathervane;Rope spools|rope;Flight goggles|goggles;Travel satchels|satchel;Signal pennants|flag;Warm tea|thermos;Landing beacons|beacon;Sky notebooks|notebook'],
    ['kitefestival','Kite Meadow','cloud','kite','Meli','Meli saves every broken kite, certain each one still remembers how to fly.','A patchwork kite can lift the village lantern higher than the finest new sail.','The lantern rises on everybody\'s scraps. The sky carries a hundred colours.','Broken wings|Patchwork cloth|Meadow frames|Shared strings|Wind rehearsal|Lantern lift|Colour parade|The patchwork sky','Patchwork kites|kite;Coloured silk|silkrolls;String spools|rope;Bamboo frames|steelbeam;Paper fans|paperfan;Festival ribbons|bow;Wind charts|map;Picnic baskets|basket;Meadow flowers|bouquet;Repair needles|tools;Paint palettes|palette;Sky lanterns|lantern'],
    ['snowpass','Snowbell Pass','alpine','bridge','Toma','Toma keeps the pass open with a bell that travellers ring for one another.','The storm buried the marker posts, but a herd has remembered the safe trail.','New markers follow the herd\'s path. The bell welcomes a reunited family.','Buried markers|Warm provisions|Animal trail|Pass repairs|Snow convoy|Bell shelter|Family crossing|Snowbell welcome','Marker poles|flag;Thermal coats|parka;Trail bells|bell;Hot flasks|thermos;Snow shovels|tools;Rope lines|rope;Mountain maps|map;Shelter canvas|tent;Ice grips|iceaxe;Soft blankets|blanket;Repair boots|workboot;Pass lanterns|lantern'],
    ['windmillridge','Windmill Ridge','alpine','windmill','Ivo','Ivo finds windmills turning in opposite directions on a lonely ridge.','Each was built for a different season. Their old plans can power one shared workshop.','The ridge hums with steady light. Ivo makes room for every changing wind.','Ridge survey|Old mill plans|Season gears|Shared workshop|Wind relay|Sail tuning|Evening power|Room for the wind','Windmill gears|gear;Sailcloth panels|linen;Workshop plans|blueprint;Wind vanes|weathervane;Repair tools|tools;Storage cells|powercell;Timber beams|steelbeam;Oil cans|jar;Work gloves|gloves;Supply baskets|basket;Wind meters|sensor;Workshop lamps|lamp'],
    ['eaglenest','Eagle Watch','alpine','nest','Suri','Suri watches an eagle trying to repair its nest with a ribbon of plastic.','The nesting cliff is beside a forgotten weather station full of useful salvage.','Clean nesting ground and a repaired station give the cliff two safe homes.','Cliff watch|Weather station|Ribbon rescue|Clean nesting ground|Station repairs|Quiet provisions|First flight|Two safe homes','Weather sensors|sensor;Nest materials|plant;Cleanup sacks|bag;Field binoculars|binoculars;Climbing ropes|rope;Repair panels|solar;Observation books|notebook;Station radios|radio;Safe gloves|gloves;Trail food|breadloaf;Camera kits|camera;Cliff beacons|beacon'],
    ['floatinggarden','Hanging Garden','cloud','garden','Lena','Lena waters a garden on an island with no spring.','Her grandmother\'s broken rain harp can collect water from the passing clouds.','Flowers open beneath the repaired harp. A thirsty island learns a new song.','Dry flower beds|Rain-harp parts|Cloud-water jars|Garden channels|Seedling relay|Harp tuning|First rainfall|The garden sings','Rain harps|lyre;Flower seedlings|plant;Water jars|jar;Garden channels|steelbeam;Cloud filters|sensor;Hanging baskets|basket;Watering cans|wateringcan;Tool rolls|tools;Garden notes|book;Silk ties|bow;Flower bouquets|bouquet;Rain lanterns|lantern'],
    ['thunderpeak','Thunder Peak','alpine','observatory','Rafi','Rafi climbs the peak to study thunder and finds the station abandoned.','Its instruments recorded a storm warning that never reached the valley.','The station broadcasts again. Science becomes a promise to look after one another.','Empty station|Instrument crates|Missed warning|Signal repairs|Valley relay|Weather calibration|Storm message|The listening peak','Weather radios|radio;Storm sensors|sensor;Station tools|tools;Safety helmets|helmet;Copper cables|cablereel;Research notebooks|notebook;Warm jackets|parka;Solar tiles|solartile;Warning flags|flag;Food flasks|thermos;Sample cases|box;Signal beacons|beacon'],
    ['airshipquay','Airship Quay','cloud','airship','Ivo','Ivo reaches a quay where every airship waits for one missing delivery.','The missing cargo is letters of invitation, not engines or fuel.','Families board for their first reunion in years. The quay opens its sky lanes.','Waiting fleet|Engine service|Invitation bags|Boarding supplies|Quay relay|Flight rehearsal|Family arrivals|Reunion above','Invitation mail|mailbundle;Engine tools|tools;Boarding tickets|transitticket;Silk sails|silkrolls;Navigation compasses|compass;Flight goggles|goggles;Travel trunks|satchel;Fuel cells|fuel;Mooring ropes|rope;Galley bread|breadloaf;Passenger blankets|blanket;Quay lights|beacon'],
    ['sunforge','Sunforge','alpine','forge','Hana','Hana\'s mountain forge runs on a mirror that cracked during the storm.','The broken pieces focus warmth in small patches perfect for a seed nursery.','One repaired mirror powers both forge and garden. Warmth finds a second purpose.','Mirror fragments|Forge tools|Seed nursery|Sun lens fittings|Warmth relay|Metalwork orders|Garden opening|A generous sun','Mirror shards|lens;Forge hammers|hammer;Seed trays|plant;Metal ingots|crystalingot;Safety goggles|goggles;Work aprons|tunic;Polishing cloth|linen;Forge tongs|tools;Nursery pots|jar;Sun prisms|lightprism;Repair gears|gear;Forge lamps|lamp'],
    ['firstflight','First Flight','cloud','kite','Ivo','Ivo must cross the last gap, but his largest kite has never carried anyone.','The island children attach their small kites beside it, sharing the lift.','Ivo crosses with the lantern map. No single wing had to carry the whole world.','Last island|Great kite frame|Small-wing parcels|Shared rigging|Flight provisions|Wind rehearsal|Keeper crossing|Many little wings','Great kite sails|kite;Rigging ropes|rope;Flight provisions|breadloaf;Child-sized kites|kite;Wind instruments|weathervane;Map cases|map;Safety harnesses|bracer;Warm gloves|gloves;Landing flags|flag;Travel goggles|goggles;Letter satchels|satchel;Dawn beacons|beacon'],
    ['junglecanopy','Canopy Camp','jungle','canopy','Nia','Nia follows a trail of fallen fruit to a camp cut off by climbing vines.','The vines shelter new nests. A raised rope path can reopen the camp without clearing them.','The canopy camp reconnects. Its lantern shines above a forest still full of birds.','Fruit trail|Camp supplies|Nesting survey|Rope walkway|Canopy relay|Field notebooks|Birdsong supper|The raised road','Canopy ropes|rope;Camp baskets|basket;Trail fruit|fruitcrate;Field binoculars|binoculars;Nest boxes|house;Canvas tents|tent;Survey notebooks|notebook;Research cameras|camera;Climbing gloves|gloves;Water flasks|thermos;Ranger maps|map;Canopy lanterns|lantern'],
    ['orchidriver','Orchid River','jungle','waterfall','Nia','Nia finds rare orchids floating past a washed-out nursery.','Their keeper has saved every seed packet in a jar tied to a tree.','A riverside nursery reopens above the flood line. The saved seeds bloom.','Floating flowers|Keeper rescue|Seed-packet jars|Raised nursery|River relay|Garden repair|First blossoms|Flowers return','Orchid seedlings|lotus;Seed packets|bag;Nursery jars|jar;Raised-bed timber|steelbeam;Garden tools|tools;River ropes|rope;Watering cans|wateringcan;Plant notebooks|book;Protective gloves|gloves;Canvas covers|tent;Flower baskets|basket;Nursery lights|lantern'],
    ['bamboovillage','Bamboo Village','jungle','village','Chen','Chen builds instruments from bamboo while the village\'s broken pipes fall silent.','One bamboo workshop can repair the water pipes as well as make music.','Water and music return together. Chen plays the village\'s first evening song.','Silent village|Bamboo bundles|Pipe workshop|Clean-water fittings|Village relay|Instrument orders|Evening rehearsal|Water and song','Bamboo poles|steelbeam;Repair fittings|tools;Clean water|watercrate;Bamboo flutes|flute;Work gloves|gloves;Village plans|blueprint;Pipe valves|gear;Garden baskets|basket;Rice sacks|bag;Hand drums|drum;Ceramic cups|cup;Village lanterns|lantern'],
    ['savannastation','Savanna Station','desert','nursery','Ayo','Ayo keeps a shaded water station along a long migration trail.','A broken pump hides a little spring that the animals still remember.','The repaired station follows the spring\'s rhythm. The migration moves safely on.','Dusty trail|Water station|Hidden spring|Pump repairs|Shaded provisions|Migration watch|Quiet welcome|The remembered spring','Pump tools|tools;Water barrels|barrel;Shade cloth|linen;Field binoculars|binoculars;Station maps|map;Safety radios|radio;Seedling pots|plant;First-aid boxes|firstaid;Camera traps|camera;Solar panels|solar;Ranger hats|cap;Trail beacons|beacon'],
    ['desertbloom','Desert Bloom','desert','garden','Zara','Zara tends a dry garden planted by someone she never met.','The planting notes reveal flowers that sleep through drought and wake after one rain.','The garden blooms overnight. Zara leaves fresh notes for its next keeper.','Sleeping garden|Planting notes|Water stores|Shade frames|Garden relay|Rain instruments|Night watch|A thousand blooms','Desert seeds|plant;Planting scrolls|scroll;Water jars|jar;Shade frames|steelbeam;Rain sensors|sensor;Garden tools|tools;Woven baskets|basket;Clay pots|amphora;Field flasks|thermos;Flower presses|book;Seed envelopes|mailbundle;Garden lanterns|lantern'],
    ['fireflyfen','Firefly Fen','jungle','pond','Nia','Nia arrives at a wetland whose fireflies have vanished from the boardwalk.','The bright lamps hide their signals. Soft shaded lanterns can light the path.','The fireflies return. Their little lights guide the evening walkers.','Quiet boardwalk|Wetland survey|Shaded lenses|Path repairs|Fen relay|Gentle lighting|Evening signals|Little lights return','Shaded lanterns|lantern;Wetland boards|board;Light lenses|lens;Field notebooks|notebook;Waders|workboot;Water sensors|sensor;Reed seedlings|plant;Repair ropes|rope;Camera kits|camera;Path markers|flag;Tea flasks|thermos;Volunteer badges|herobadge'],
    ['redwoodtrail','Redwood Trail','greenwood','tree','Ash','Ash finds a tiny seed growing in the hollow of a fallen giant.','The hollow trunk is home to a whole woodland community. The seed needs room nearby.','A new trail protects both old trunk and young tree. The forest keeps two generations.','Fallen giant|Young seedling|Hollow homes|Gentle path|Ranger relay|Tree nursery|Trail opening|Two generations','Tree seedlings|plant;Trail maps|map;Ranger tools|tools;Habitat boxes|house;Rope rails|rope;Timber markers|flag;Seed baskets|basket;Nature notebooks|notebook;Water cans|wateringcan;Bird binoculars|binoculars;Work gloves|gloves;Forest lanterns|lantern'],
    ['glaciergarden','Glacier Garden','alpine','glasshouse','Nia','Nia finds a greenhouse warmed by the last working lamp in a glacier camp.','The keeper is saving seeds from places the crew may never see again.','The greenhouse becomes a living seed library. Its lantern carries the promise of spring.','Ice camp|Greenhouse panes|Seed library|Warm-bed repairs|Glacier relay|Gentle heating|Living catalogue|Spring kept safe','Seed-library boxes|box;Greenhouse glass|lens;Warm soil sacks|bag;Solar heaters|heater;Garden tools|tools;Research sensors|sensor;Seed notebooks|book;Thermal gloves|gloves;Seedling trays|plant;Water flasks|thermos;Repair tiles|solartile;Greenhouse lamps|lamp'],
    ['monsooncamp','Monsoon Camp','jungle','canopy','Devi','Devi turns a school veranda into a shelter before the first heavy rain.','The pupils have already drawn a map of safe dry routes through the village.','Their map guides the final family home. Lessons begin with a story of helping.','First rain|Dry blankets|Pupil maps|Shelter canopy|Village relay|Warm meal kits|Last family home|A lesson in care','Dry blankets|blanket;Shelter canvas|tent;Pupil maps|map;Meal kits|takeaway;Clean water|watercrate;First-aid cases|firstaid;School books|bookstack;Repair boots|workboot;Rain jackets|parka;Signal radios|radio;Art pencils|pencils;Shelter lanterns|lantern'],
    ['wildheart','Wildheart Gate','jungle','arch','Nia','Nia reaches a gate where old maps mark the wild as empty space.','Her notebooks reveal homes, migrations and gardens hidden between the roads.','The new map leaves room for every living neighbour. Another lantern joins the route.','Old map gate|Field notebooks|Hidden homes|Habitat supplies|Wildlife relay|New-map ink|Keeper gathering|Room for the wild','Field notebooks|bookstack;Map ink|jar;Ranger compasses|compass;Habitat kits|house;Forest seeds|plant;Bird cameras|camera;Trail rope|rope;Supply baskets|basket;Research badges|herobadge;Survey lenses|lens;Keeper letters|mailbundle;Wildheart lanterns|lantern'],
    ['copperclock','Copper Clock','workshop','clock','Tess','Tess returns to the clocktower where she first learned to make things tick.','The clock stopped at the hour her teacher retired, leaving a note in its gears.','The repaired clock rings for the teacher\'s welcome party, not the start of work.','Stopped tower|Copper gears|Teacher note|Clock-face repairs|Workshop relay|Bell tuning|Welcome parcels|Time for friends','Copper gears|gear;Clock hands|clock;Teacher letters|mailbundle;Repair tools|tools;Brass bells|bell;Oil jars|jar;Workshop goggles|goggles;Pendulum weights|crystalingot;Party ribbons|bow;Tea cups|cup;Blueprint books|blueprint;Tower lamps|lamp'],
    ['automatonalley','Automaton Lane','workshop','robot','Tess','Tess finds a delivery robot still waiting outside a vanished address.','Its parcel holds a toy repaired for a child who is now the lane\'s oldest resident.','The late gift arrives. The robot receives a new route and a warm welcome.','Waiting robot|Address search|Toy workshop|Memory parcels|Lane relay|Robot repairs|Long-awaited gift|A new route','Robot motors|gear;Address books|book;Toy parts|teddy;Circuit boards|circuitboard;Power cells|powercell;Repair kits|tools;Sensor lenses|sensor;Parcel labels|tag;Memory letters|mailbundle;Robot kits|robotkit;Cable reels|cablereel;Lane beacons|beacon'],
    ['glasslab','Glass Lab','cyber','glasshouse','Uma','Uma creates glass that shows colours too faint for anyone else to notice.','A gardener asks for a lens to spot thirsty seedlings before they wilt.','The first useful lens leaves the lab. Uma calls it the kinder microscope.','Colour samples|Lens workshop|Garden request|Glass polishing|Lab relay|Seedling scans|Useful invention|A kinder lens','Glass lenses|lens;Microscopes|microscope;Seedling trays|plant;Lab notebooks|notebook;Polishing kits|brush;Protective goggles|goggles;Sample jars|jar;Colour charts|colourchart;Sensor boards|circuitboard;Glass prisms|lightprism;Research tablets|tablet;Lab lights|lamp'],
    ['railworkshop','Rail Workshop','workshop','rail','Bo','Bo mends a little railway built to bring books to faraway schools.','The final carriage is a travelling classroom with no seats installed.','The classroom rolls out with room for every pupil. Bo rides along to tell stories.','Empty carriage|Track timbers|Classroom plans|Seat fittings|Rail relay|Library shelves|First passengers|The travelling class','Rail sections|steelbeam;Carriage seats|chair;Library books|bookstack;Track tools|tools;Safety signals|trafficlight;School notebooks|notebook;Repair wheels|wheel;Window glass|lens;Classroom globes|globe;Seat cushions|pillow;Boarding tickets|transitticket;Rail lamps|lantern'],
    ['neonnetwork','Neon Network','cyber','signal','Tess','Tess follows flickering signs to a neighbourhood whose messages never arrive.','An overloaded network gives adverts priority over letters from home.','The repaired network carries family messages first. Every sign becomes a welcome.','Lost messages|Network parts|Priority letters|Signal repairs|City relay|Cable testing|Homeward news|A brighter welcome','Network chips|microchip;Letter drives|serverdrive;Cable reels|cablereel;Signal boards|circuitboard;Router kits|sensor;Repair tablets|tablet;Power cells|powercell;Toolboxes|toolbox;Message notebooks|notebook;Street lights|beacon;Glass panels|lens;Service badges|herobadge'],
    ['solarvillage','Solar Village','cyber','solar','Eli','Eli\'s village has sunshine all day and dark kitchens every evening.','The school roof has room for panels and the old bakery can hold shared batteries.','The first evening lights stay on for supper. Eli invites the entire street.','Sunlit roofs|Panel delivery|Shared batteries|Roof repairs|Energy relay|Storage testing|Evening kitchens|Supper in the light','Solar panels|solar;Storage batteries|powercell;Roof brackets|tools;Circuit boards|circuitboard;Cable coils|cablereel;Safety helmets|hardhat;Energy meters|sensor;Repair tablets|tablet;Kitchen lamps|lamp;Supper baskets|basket;School notes|book;Welcome banners|flag'],
    ['maglevyard','Maglev Yard','cyber','rail','Tess','Tess visits a yard where a silent train waits for its first journey.','Its clever engine is ready, but nobody has built an accessible boarding ramp.','The ramp opens with the line. The fastest route starts by making room for everyone.','Silent train|Magnet coils|Boarding plans|Ramp fittings|Yard relay|Safety testing|Open platform|Everyone aboard','Magnet coils|magnet;Platform plans|blueprint;Ramp panels|steelbeam;Train chips|microchip;Safety lights|trafficlight;Rail sensors|sensor;Tool kits|toolbox;Boarding passes|transitticket;Power cells|powercell;Repair cables|cablereel;Seat cushions|pillow;Platform beacons|beacon'],
    ['musicfactory','Melody Works','workshop','music','Tess','Tess discovers a workshop full of instruments nobody has finished.','Each maker waited for the others to decide what the song should be.','The instruments play different parts of one tune. Tess finally takes a night off.','Unfinished notes|String orders|Shared score|Instrument repairs|Melody relay|Quiet rehearsal|First orchestra|One shared tune','Guitar strings|guitar;Drum skins|drum;Flute pipes|flute;Piano keys|keyboard;Music notebooks|book;Brass bells|bell;Repair tools|tools;Speaker cones|speaker;Polishing cloth|linen;Microphone kits|mic;Concert tickets|ticket;Stage lanterns|lantern'],
    ['tinyfoundry','Tiny Foundry','workshop','forge','Mo','Mo casts tiny replacement parts for machines everyone else would throw away.','The smallest order is a hinge that can reopen a closed neighbourhood library.','The library door swings wide. Mo saves a shelf for the tools that made it possible.','Small orders|Metal stock|Library hinge|Careful casting|Foundry relay|Door repairs|Book arrivals|The little hinge','Metal ingots|crystalingot;Hinge moulds|ringmould;Foundry hammers|hammer;Library books|bookstack;Precision drills|drill;Safety goggles|goggles;Work gloves|gloves;Measuring tools|tapemeasure;Repair gears|gear;Parts boxes|box;Workshop plans|blueprint;Foundry lamps|lamp'],
    ['tomorrowfair','Tomorrow Fair','cyber','festival','Tess','Tess brings her repaired clock to a fair of wonderful unfinished inventions.','Every invention works best when someone tells its maker what they need.','The fair becomes a listening workshop. Its lantern shines on useful tomorrow.','Fair invitations|Inventor tables|Neighbour wishes|Workshop kits|Fair relay|Helpful prototypes|Evening concert|Useful tomorrow','Prototype robots|robotkit;Neighbour letters|mailbundle;Inventor notebooks|notebook;Solar kits|solar;Repair toolboxes|toolbox;Listening sensors|sensor;Display screens|tablet;Fair banners|flag;Concert flutes|flute;Storage cells|powercell;Gift boxes|gift;Tomorrow beacons|beacon'],
    ['teacourtyard','Tea Courtyard','village','garden','Sol','Sol visits a tea garden whose keeper still sets two cups every morning.','The second cup is for an old friend whose letters stopped after the storm.','A fresh letter arrives with your delivery. The tea finally has someone to share it.','Two empty cups|Tea leaves|Lost-letter trail|Courtyard repairs|Tea relay|Letter arrival|Shared breakfast|A cup for a friend','Tea jars|jar;Porcelain cups|cup;Old letters|mailbundle;Garden flowers|bouquet;Honey pots|jar;Courtyard stools|chair;Silk napkins|linen;Breakfast buns|breadloaf;Kettle parts|kettle;Recipe books|book;Woven trays|basket;Tea lanterns|lantern'],
    ['noodlequarter','Noodle Quarter','kitchen','market','Mei','Mei opens a noodle stall using a recipe with its final line torn away.','The missing line says to save a bowl for the person who arrives last.','The final diner sits down as the lantern lights. Mei keeps the lesson on the menu.','Torn recipe|Noodle ingredients|Missing line|Stall repairs|Kitchen relay|Broth supplies|Last diner|One more bowl','Noodle bowls|soupbowl;Broth jars|jar;Recipe pages|scroll;Chef aprons|tunic;Bamboo chopsticks|cutlery;Fresh herbs|plant;Steam baskets|basket;Soup ladles|cutlery;Rice sacks|bag;Menu boards|menu;Takeaway boxes|takeaway;Stall lanterns|lantern'],
    ['pizzapiazza','Pizza Piazza','kitchen','oven','Luca','Luca\'s pizza oven is cold on the night of the town\'s reunion.','A neighbour brings a smaller portable oven and asks everyone to cook in turns.','Many small ovens warm the square. The reunion tastes like everybody\'s home.','Cold oven|Dough baskets|Neighbour oven|Piazza tables|Pizza relay|Shared recipes|Reunion orders|Everybody\'s table','Pizza dough|breadloaf;Tomato jars|saucebottle;Portable ovens|heater;Fresh basil|plant;Pizza boxes|takeaway;Wooden paddles|paddle;Dinner plates|plate;Flour sacks|floursack;Table cloths|linen;Recipe notes|notebook;Oven gloves|keepergloves;Piazza lights|festoon'],
    ['spicegarden','Spice Garden','village','herbs','Sol','Sol follows a wonderful smell to a garden with herbs from distant homes.','Its keeper learned each seed\'s name from a traveller who once needed a meal.','The seed boxes go out with recipe cards. New kitchens begin a story of welcome.','Scented path|Spice seeds|Traveller recipes|Garden beds|Seed relay|Recipe parcels|Shared harvest|A welcome grows','Spice sacks|spices;Herb seedlings|plant;Recipe cards|notebook;Seed baskets|basket;Clay pots|amphora;Garden spades|tools;Watering cans|wateringcan;Honey jars|jar;Travel satchels|satchel;Paper envelopes|mailbundle;Harvest knives|knife;Garden lanterns|lantern'],
    ['harvesthill','Harvest Hill','village','windmill','Sol','Sol reaches the hill as a storm threatens the first shared harvest.','The old mill has empty lofts large enough to dry every neighbour\'s grain.','The lofts fill and the crop survives. The first loaf is divided a hundred ways.','Harvest morning|Grain baskets|Mill lofts|Drying racks|Hill relay|Bread supplies|Harvest supper|The shared loaf','Harvest grain|wheat;Drying racks|board;Grain baskets|basket;Mill tools|hammer;Flour sacks|floursack;Bread loaves|breadloaf;Rain covers|linen;Work boots|workboot;Hot soup|soupbowl;Harvest aprons|tunic;Supper plates|plate;Hill lanterns|lantern'],
    ['orchardlane','Orchard Lane','village','orchard','Iris','Iris picks fruit from an orchard planted for children who had no garden.','The storm knocked down the gate but left the oldest tree full of apples.','A new low gate welcomes the whole school. Iris sends the first baskets to its kitchen.','Fallen gate|Apple baskets|Oldest tree|Orchard repairs|Fruit relay|School recipes|Garden picnic|The open orchard','Apple baskets|fruitcrate;Gate timbers|steelbeam;Garden tools|tools;School aprons|tunic;Fruit jars|jar;Picnic blankets|blanket;Water cans|wateringcan;Recipe books|book;Tree seedlings|plant;School lunch boxes|box;Paper napkins|linen;Orchard lanterns|lantern'],
    ['snowcafe','Snowflake Cafe','alpine','village','Sol','Sol finds a cafe serving hot drinks for free to travellers caught in the snow.','The keeper\'s dwindling supplies are being replaced by gifts from those same travellers.','The shelves fill before sunset. The cafe becomes a promise that kindness travels back.','Warm doorstep|Drink flasks|Traveller gifts|Cafe repairs|Snow relay|Pantry parcels|Evening guests|Kindness returns','Hot drink flasks|thermos;Coffee beans|bag;Travel blankets|blanket;Gift baskets|basket;Milk jars|bottle;Cafe mugs|mug;Pantry bread|breadloaf;Window panes|lens;Warm mittens|gloves;Soup bowls|soupbowl;Thank-you letters|mailbundle;Cafe lights|lantern'],
    ['paperstreet','Paper Street','village','archive','Sol','Sol stops at a street of paper shops that smells like a childhood kitchen.','A printer has kept old family recipes as carefully as the town\'s official records.','The printers make a recipe book for the reunion. Every family receives a blank page.','Paper shops|Old recipes|Family memories|Print repairs|Street relay|Book binding|Reunion copies|A page for you','Paper stacks|notebook;Recipe scrolls|scroll;Printer tools|tools;Ink bottles|jar;Binding ribbons|bow;Book covers|book;Family letters|mailbundle;Printing blocks|seal;Pencil bundles|pencils;Paper fans|paperfan;Delivery satchels|satchel;Street lanterns|lantern'],
    ['carnivalcamp','Carnival Camp','village','festival','Sol','Sol follows a travelling carnival whose kitchen feeds the crews of every show.','The smallest performer has written a menu with dishes from all the places they visited.','The crews cook the menu together. The carnival carries a feast from world to world.','Travelling camp|Kitchen crates|Little menu|Tent repairs|Carnival relay|Show-time meals|Shared recipes|The travelling feast','Carnival tickets|ticket;Menu notebooks|menu;Kitchen baskets|basket;Canvas tents|tent;Stage lights|festoon;Meal boxes|takeaway;Juggling balls|ball;Musician flutes|flute;Cooking pans|pan;Costume ribbons|bow;Festival banners|flag;Camp lanterns|lantern'],
    ['grandfeast','Grand Feast','kitchen','festival','Sol','Sol lays a hundred empty places at a table stretching through the village.','Every keeper arrives with one ingredient and a story from the road.','The table fills. Sol writes the final recipe: make enough room for one more.','Empty table|Keeper recipes|Hundred ingredients|Table fittings|Kitchen relay|Feast orders|Stories at supper|Room for one more','Feast platters|plate;Keeper recipe books|book;Bread baskets|basket;Soup cauldrons|pan;Fruit crates|fruitcrate;Tea kettles|kettle;Table linens|linen;Flower bouquets|bouquet;Welcome cards|mailbundle;Serving cutlery|cutlery;Celebration cakes|layercake;Feast lanterns|lantern'],
    ['riverclay','River Clay','temple','pottery','Asha','Asha finds a riverside workshop where a broken bowl has been mended with gold.','The potter says its cracks are the map of every hand that saved it.','The community repairs its market bowls. Asha keeps the story, not the treasure.','River workshop|Clay baskets|Golden repair|Kiln fittings|Pottery relay|Market orders|Shared workshop|The saved bowl','Clay bowls|porcelain;Pottery jars|amphora;Repair gold|coins;Kiln bricks|brickstack;Brush bundles|brush;Workshop aprons|tunic;Clay sacks|bag;Pattern scrolls|scroll;Glaze bottles|jar;Market baskets|basket;Carved seals|seal;Kiln lanterns|lantern'],
    ['hillcitadel','Hill Citadel','castle','castle','Asha','Asha follows a faded supply list into a hill citadel with empty kitchens.','Its oldest record tells of a baker who fed the town during an earlier siege.','The kitchens open as a public bakery. The forgotten baker\'s name returns to the gate.','Empty kitchens|Supply records|Baker story|Oven repairs|Citadel relay|Grain deliveries|Public bakery|The remembered baker','Ancient grain|wheat;Baker scrolls|scroll;Oven bricks|brickstack;Trade baskets|basket;Kitchen tools|tools;Linen tunics|tunic;Water jars|amphora;Bread loaves|breadloaf;Gate keys|oldkey;Carved signs|board;Market coins|coins;Citadel lanterns|lantern'],
    ['reedlibrary','Reed Library','temple','archive','Asha','Asha reaches a river library whose scrolls were scattered by floodwater.','A schoolchild copied the oldest tales onto reed tablets before the rain came.','The copied tales rebuild the library. The child becomes its youngest keeper.','Scattered scrolls|Reed tablets|Pupil copies|Shelf repairs|Library relay|Ink orders|Tales restored|The young keeper','Reed tablets|board;Story scrolls|scroll;Ink pots|jar;Library shelves|steelbeam;Writing reeds|pencils;Book satchels|satchel;Clay seals|seal;Reading lamps|lamp;Linen wraps|linen;River baskets|basket;Archive keys|oldkey;Keeper badges|herobadge'],
    ['bronzesmith','Bronze Smithy','temple','forge','Asha','Asha visits a smithy famous for shields and hears a child ask for a garden spade.','The smith has never made one, but the oldest mould is a humble farming tool.','The first tools go to a shared garden. The smithy makes a different kind of legacy.','Shield workshop|Old moulds|Garden request|Forge fittings|Smithy relay|Tool orders|Shared garden|A useful legacy','Bronze tools|hammer;Garden spades|tools;Old moulds|ringmould;Metal ingots|crystalingot;Seed baskets|basket;Forge aprons|tunic;Water jars|amphora;Charcoal sacks|bag;Garden scrolls|scroll;Work gloves|gloves;Trade scales|gemscale;Smithy lanterns|lantern'],
    ['oasiscaravan','Oasis Caravan','desert','market','Asha','Asha meets a caravan carrying a letter between two towns that stopped trading.','The letter is an apology written by a merchant\'s grandchild.','The first shared caravan departs. Two markets find something more valuable than gold.','Oasis arrival|Caravan stores|Grandchild letter|Well repairs|Desert relay|Trade parcels|Shared market|Roads reopened','Caravan letters|mailbundle;Water flasks|thermos;Spice sacks|spices;Silk bolts|silkrolls;Trade ledgers|book;Canvas shelters|tent;Brass compasses|compass;Tea jars|jar;Carpet rolls|rug;Merchant seals|seal;Date baskets|fruitcrate;Oasis lanterns|lantern'],
    ['mountainloom','Mountain Loom','alpine','market','Asha','Asha visits a weaving house whose patterns have never been written down.','The oldest weaver teaches them to a pupil who sees the colours differently.','A new pattern joins the old ones. The loom\'s story keeps growing instead of ending.','Weaving house|Wool baskets|Pattern lessons|Loom repairs|Mountain relay|Colour threads|Pupil tapestry|A growing pattern','Wool bundles|blanket;Loom frames|steelbeam;Colour threads|silkrolls;Pattern books|book;Weaving shuttles|tools;Cloth rolls|linen;Wooden spools|gear;Tapestry carpets|rug;Needle cases|box;Dye jars|jar;Warm shawls|cloak;Loom lanterns|lantern'],
    ['seafarerhall','Seafarer Hall','harbour','sailboat','Asha','Asha reaches a hall where sailors carved their journeys into wooden beams.','One blank beam belongs to a cook whose voyages were never recorded.','The cook\'s stories fill the new carving. Every hand aboard earns a place in the hall.','Carved hall|Supply barrels|Blank beam|Hall repairs|Seafarer relay|Voyage provisions|Cook\'s carving|Every hand aboard','Voyage barrels|barrel;Carving chisels|tools;Timber beams|steelbeam;Sailcloth rolls|linen;Cooking pots|pan;Rope coils|rope;Ship models|longship;Voyage scrolls|scroll;Warm blankets|blanket;Harbour fish baskets|fishbasket;Story maps|map;Hall lanterns|lantern'],
    ['mosaiccourt','Mosaic Court','temple','mosaic','Asha','Asha discovers a courtyard mosaic with an empty square at its centre.','The design was left unfinished so each new generation could add a tile.','Neighbours fill a new border and leave the centre open. The story still has room to grow.','Empty square|Tile baskets|Unfinished plan|Court repairs|Mosaic relay|Colour sorting|Neighbour tiles|Room for the future','Mosaic tiles|mosaic;Colour charts|colourchart;Court plans|blueprint;Stone blocks|stoneblock;Tile tools|tools;Water jars|amphora;Pattern scrolls|scroll;Linen cloths|linen;Flower baskets|basket;Polishing brushes|brush;Trade tokens|coins;Court lanterns|lantern'],
    ['starobservatory','Old Star Dome','temple','observatory','Asha','Asha opens an old observatory whose star charts end on one unfinished night.','A note says the astronomer left to guide a lost caravan and never returned to the page.','New keepers finish the chart from the road. The missing star becomes a sign of kindness.','Dusty dome|Star charts|Unfinished night|Lens repairs|Dome relay|Sky measurements|Roadside stars|The missing star','Star charts|map;Telescope lenses|lens;Brass compasses|compass;Astronomy scrolls|scroll;Dome tools|tools;Glass prisms|lightprism;Time dials|sundial;Ink jars|jar;Warm cloaks|cloak;Caravan lanterns|lantern;Measuring rulers|ruler;Keeper notebooks|notebook'],
    ['memorygate','Memory Gate','archive','arch','Asha','Asha reaches a gate carrying the names of rulers but none of its builders.','The letters she restored reveal potters, cooks, weavers and couriers who kept its road alive.','The names join the gate. Asha sends their stories with the final history lantern.','Gate records|Restored letters|Everyday names|Archive shelves|Memory relay|Story copies|New inscriptions|Those who carried','Restored letters|mailbundle;Story books|bookstack;Carving tools|tools;Archive scrolls|scroll;Gate stone|stoneblock;Ink bottles|jar;Builder seals|seal;Linen covers|linen;Memory satchels|satchel;Trade maps|map;Name tablets|board;History lanterns|lantern'],
    ['cometcamp','Comet Camp','cosmos','observatory','Lumi','Lumi waits at a camp for a comet that returns only once in a lifetime.','The best viewing place is beyond a broken path, where the oldest camper cannot walk.','A new ramp opens before nightfall. Everybody watches the same brilliant sky.','Comet watch|Viewing lenses|Accessible path|Ramp supplies|Camp relay|Telescope tuning|Night gathering|One shared sky','Telescope lenses|lens;Ramp panels|steelbeam;Star notebooks|notebook;Camp blankets|blanket;Comet maps|map;Solar batteries|powercell;Warm flasks|thermos;Signal beacons|beacon;Viewing goggles|goggles;Repair tools|tools;Camp tents|tent;Comet crystals|facetedgem'],
    ['moonorchard','Moon Orchard','cosmos','orchard','Lumi','Lumi finds an orchard planted from seeds carried on the first moon voyage.','Its caretaker kept the last fruit to share when another visitor finally arrived.','The fruit becomes seeds for new gardens. A patient gift travels farther than its giver.','Patient orchard|Moon seedlings|Last-fruit basket|Garden repairs|Orchard relay|New seed boxes|Visitor supper|A gift of gardens','Moon seedlings|plant;Fruit baskets|fruitcrate;Seed cases|box;Garden sensors|sensor;Solar tiles|solartile;Water tanks|oxygen;Garden tools|tools;Research notebooks|notebook;Visitor cups|cup;Orchard gloves|gloves;Light prisms|lightprism;Moon lamps|lamp'],
    ['aurorabazaar','Aurora Bazaar','cosmos','market','Lumi','Lumi follows coloured lights to a bazaar that trades wishes written on paper.','The smallest wish is simply for someone to fix an old reading lamp.','The lamp lights a new wish: more books. The bazaar learns to turn wishes into work.','Paper wishes|Reading lamps|Smallest request|Market repairs|Aurora relay|Library parcels|Wish-makers|Wishes with hands','Wish letters|mailbundle;Reading lamps|lamp;Story books|bookstack;Aurora crystals|facetedgem;Repair kits|tools;Paper fans|paperfan;Market baskets|basket;Colour ribbons|bow;Light prisms|lightprism;Tea jars|jar;Star charts|map;Bazaar lanterns|lantern'],
    ['dreamstation','Dream Station','dream','rail','Lumi','Lumi boards a station whose trains carry dreams nobody dared begin.','One carriage holds an empty notebook waiting for its first imperfect sketch.','The notebook leaves with a young inventor. The station sends unfinished dreams into daylight.','Waiting dreams|Blank notebooks|First sketch|Carriage repairs|Dream relay|Inventor tools|Daylight tickets|Begin imperfectly','Blank notebooks|notebook;Sketch pencils|pencils;Inventor tools|tools;Dream tickets|transitticket;Soft pillows|pillow;Colour palettes|palette;Clock parts|clock;Toy robots|robotkit;Star blankets|blanket;Travel bags|satchel;Letter bundles|mailbundle;Dream lanterns|lantern'],
    ['crystalchoir','Crystal Choir','dream','music','Lumi','Lumi hears a crystal choir with one silent instrument at its centre.','It was built for a keeper who believed their voice was too small to matter.','The quiet note completes the harmony. The choir shines with every different voice.','Silent crystal|Choir instruments|Keeper invitation|Stage repairs|Harmony relay|Gentle rehearsal|The quiet note|Every voice matters','Singing crystals|facetedgem;Choir bells|bell;Keeper letters|mailbundle;String instruments|lyre;Stage lanterns|lantern;Music notebooks|book;Soft mallets|hammer;Glass prisms|lightprism;Concert ribbons|bow;Warm tea|thermos;Listening lenses|sensor;Choir badges|herobadge'],
    ['planetarium','Little Planets','cosmos','planet','Lumi','Lumi finds a planetarium where the model of home is missing.','The keeper has not finished it because no map shows all the places people care about.','Your lantern map becomes the model. Home is drawn as a hundred connected stories.','Missing home|Model parts|Lantern map|Dome repairs|Planet relay|Star calibration|Connected model|A map of home','Planet models|globe;Lantern maps|map;Telescope lenses|lens;Model gears|gear;Star projectors|beacon;Dome tools|tools;Glass panels|lens;Orbit notebooks|notebook;Solar cells|solartile;Keeper postcards|mailbundle;Colour charts|colourchart;Planet lamps|lamp'],
    ['wishharbour','Wish Harbour','dream','sailboat','Lumi','Lumi reaches a harbour where paper boats carry promises to the horizon.','A keeper has spent years waiting for their boat to return instead of starting the journey.','The keeper takes the first real boat out. A promise becomes a path.','Paper boats|Voyage baskets|Waiting keeper|Boat repairs|Harbour relay|Promise letters|First departure|A promise moves','Paper boats|reedboat;Promise letters|mailbundle;Voyage baskets|basket;Sailcloth|linen;Navigation compasses|compass;Harbour ropes|rope;Travel flasks|thermos;Warm cloaks|cloak;Journey maps|map;Boat tools|tools;Signal flags|flag;Wish lanterns|lantern'],
    ['lanternlibrary','Lantern Library','archive','archive','Lumi','Lumi brings the lantern map to a library with a shelf waiting for every world.','The stories are different, but each begins with someone carrying what another person needs.','The last empty shelf holds your notebook. The library keeps a place for the next journey.','Empty shelves|Keeper books|Shared beginning|Library fittings|Story relay|Map binding|Courier notebook|A place for tomorrow','Keeper storybooks|bookstack;Courier notebooks|notebook;Map fragments|map;Shelf timbers|steelbeam;Library keys|oldkey;Ink jars|jar;Binding ribbons|bow;Reading lamps|lamp;Letter satchels|satchel;Archive seals|seal;Welcome cards|mailbundle;Library lanterns|lantern'],
    ['hundreddawn','Hundred Dawn','dream','festival','Lumi','Lumi hangs the lantern map over a square where the keepers are gathering.','One final delivery remains: an empty parcel for whatever you choose to carry next.','A hundred lanterns shine on a road built by small acts of care. Your next story begins at home.','Gathering square|Keeper invitations|Lantern frames|Shared table|Final road relay|Homeward parcels|The empty parcel|A hundred dawns','Keeper invitations|mailbundle;Lantern frames|lantern;Map folios|map;Flower gifts|bouquet;Feast bread|breadloaf;Story notebooks|notebook;Celebration ribbons|bow;Music bells|bell;Welcome baskets|basket;Dawn prisms|lightprism;Empty gift boxes|gift;Courier badges|herobadge']
  ];
  const worlds=rows.map((r,i)=>{
    const [id,name,scene,landmark,keeper,opening,turn,ending,stageText,cargo]=r;
    const chapter=Object.keys(chapters).find(key=>{
      const starts={greenwood:0,tidebound:8,skyroads:18,wildheart:28,clockwork:38,hearthside:48,echoes:58,starlight:68};
      const start=starts[key],end=key==='starlight'?77:starts[Object.keys(chapters)[Object.keys(chapters).indexOf(key)+1]];
      return i>=start&&i<end;
    });
    const c=chapters[chapter],stages=stageText.split('|'),entries=cargo.split(';');
    const priorityCopy=entries.slice(0,3).map(e=>e.split('|')[0].replace(/^(.*) bundles$/,'$1')).join(' · ');
    return {id,name,chapter,scene,landmark,keeper,backdrop:'./assets/worlds/places/'+id+'.png',location:26+i,category:name+' supplies',badge:chapter==='greenwood'?'ARCHER':chapter==='tidebound'?'TIDES':chapter==='skyroads'?'SKY':chapter==='wildheart'?'WILD':chapter==='clockwork'?'MAKERS':chapter==='hearthside'?'HEARTH':chapter==='echoes'?'HISTORY':'STARS',
      accent:c.accent,tempo:102+(i*7%21),priority:'KEEPER SUPPLIES',priorityCopy,
      tag:`${stages[0]}. ${keeper} needs a courier.`,stages,cargo,
      lore:{opening,turn,ending},
      stories:[opening,`${keeper} readies ${name.toLowerCase()}. Bring the first keeper supplies to every dock.`,turn,
        `${stages[3]} opens a new route. ${keeper} needs careful loads as the docks change.`,
        `Keep ${stages[4].toLowerCase()} moving. Your deliveries help the neighbours finish what they began.`,
        `${stages[5]} brings the plan together. Protect fragile gifts and watch each new dock position.`,
        `${stages[6]} is almost ready. One precise convoy will carry the community into its final chapter.`,ending],
      music:{file:id+'-lantern.mp3',title:name+' — Lantern Road',voice:c.voice,key:[48,50,45,43,53,47,40][i%7],motif:i,chapter}
    };
  });
  return {title,prologue,chapters,worlds};
});
